#!/usr/bin/env bash
#
# Provisions everything a new Project needs — Neon, Google Cloud (Artifact Registry,
# Cloud Run, the Workload Identity deploy identity), Vercel, Sentry, Gemini and
# Resend — and leaves every value in this repository's GitHub secrets and variables,
# where the deploy workflows read them. The Loops run from your terminal (ADR 0009),
# so nothing here provisions a Claude token.
# Run it from the repository root. Re-running is safe: it reuses what already exists.
#
# Generated by the /wizard skill; a wizard walks a human through a manual procedure,
# step by step.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# Nothing here writes a secret to disk or prints one: every captured secret goes
# straight to `gh secret set`. Local development needs none of them — .env.example
# ships defaults (EMAIL_TRANSPORT=capture, LLM_PROVIDER=mock) that work offline.

RECORD_FILE="${RECORD_FILE:-.provisioned.json}"
RECORD_ARGS=()

# fail "..." stops the wizard on something the human must fix first.
fail() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; exit 1; }

# record KEY VALUE remembers a created resource for .provisioned.json. Identifiers
# and URLs only — never a secret value.
record() {
  RECORD_ARGS+=(--arg "$1" "$2")
  printf '  %s✓ recorded%s %s\n' "$GREEN" "$RESET" "$1"
}

record_write() {
  (( ${#RECORD_ARGS[@]} )) || return 0
  jq -n "${RECORD_ARGS[@]}" '$ARGS.named' > "$RECORD_FILE"
  note "resources recorded in $RECORD_FILE (gitignored)"
}

# set_gcp_secret NAME VALUE stores a value in Secret Manager and lets the Cloud Run
# runtime service account read it. The value reaches gcloud on stdin, so it never
# touches disk or the terminal. Re-runs add a new version rather than replacing the
# secret, which is what rotation looks like. Needs $GCP_PROJECT_ID and $RUNTIME_SA.
GCP_SECRETS=()
set_gcp_secret() {
  local name="$1" value="$2"
  gcloud secrets describe "$name" --project="$GCP_PROJECT_ID" >/dev/null 2>&1 ||
    gcloud secrets create "$name" --replication-policy=automatic \
      --project="$GCP_PROJECT_ID" >/dev/null
  printf '%s' "$value" | gcloud secrets versions add "$name" --data-file=- \
    --project="$GCP_PROJECT_ID" >/dev/null
  gcloud secrets add-iam-policy-binding "$name" --role=roles/secretmanager.secretAccessor \
    --member="serviceAccount:$RUNTIME_SA" --project="$GCP_PROJECT_ID" >/dev/null
  GCP_SECRETS+=("$name")
  printf '  %s✓ stored%s %s in Secret Manager\n' "$GREEN" "$RESET" "$name"
}

TOTAL_STAGES=10

banner "Provision this Project"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Prerequisites"
say "This wizard drives the vendor CLIs and falls back to a dashboard only where"
say "no CLI covers a step. It needs all of these:"
missing=""
for tool in gh jq gcloud vercel neonctl openssl; do
  if command -v "$tool" >/dev/null 2>&1; then step "$tool ✓"; else warn "$tool is missing"; missing="$missing $tool"; fi
done
if [[ -n "$missing" ]]; then
  note "install:$missing — brew install gh jq google-cloud-sdk; npm i -g vercel neonctl"
  confirm "Carry on anyway (stages needing a missing CLI will fail)?" || exit 1
fi
gh auth status >/dev/null 2>&1 || fail "run 'gh auth login' first"
REPO=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
SLUG=${REPO##*/}
say "GitHub repository: $REPO"
record repository "$REPO"
pause "Provisioning $SLUG. Enter to continue."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Neon: Postgres"
say "Creating the Project's database. A project of this name is reused, not replaced."
neonctl auth >/dev/null 2>&1 || pause "A browser opened for Neon login. Enter when done."
neon_id=$(neonctl projects list --output json | jq -r --arg n "$SLUG" \
  'first((.projects // [])[] | select(.name == $n) | .id) // empty')
if [[ -z "$neon_id" ]]; then
  neon_id=$(neonctl projects create --name "$SLUG" --output json | jq -r '.project.id')
  say "created Neon project $neon_id"
else
  say "reusing Neon project $neon_id"
fi
DATABASE_URL=$(neonctl connection-string --project-id "$neon_id" --pooled)
say "connection string captured; it goes into Secret Manager in stage 7, once GCP exists"
record neon_project_id "$neon_id"
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: project, APIs, Artifact Registry"
ask GCP_PROJECT_ID "Google Cloud project id (e.g. $SLUG-prod):"
[[ -n "$GCP_PROJECT_ID" ]] || fail "a Google Cloud project id is required"
ask GCP_REGION "Cloud Run region [europe-west1]:"
GCP_REGION=${GCP_REGION:-europe-west1}
gcloud projects describe "$GCP_PROJECT_ID" >/dev/null 2>&1 ||
  gcloud projects create "$GCP_PROJECT_ID"
open_url "https://console.cloud.google.com/billing/linkedaccount?project=$GCP_PROJECT_ID"
step "Link a billing account — Cloud Run's free tier still requires one."
pause "Enter once billing is linked."
gcloud services enable run.googleapis.com artifactregistry.googleapis.com \
  iamcredentials.googleapis.com sts.googleapis.com secretmanager.googleapis.com \
  --project "$GCP_PROJECT_ID"
GCP_ARTIFACT_REPOSITORY=api
gcloud artifacts repositories describe "$GCP_ARTIFACT_REPOSITORY" \
  --location="$GCP_REGION" --project="$GCP_PROJECT_ID" >/dev/null 2>&1 ||
  gcloud artifacts repositories create "$GCP_ARTIFACT_REPOSITORY" \
    --repository-format=docker --location="$GCP_REGION" --project="$GCP_PROJECT_ID"
set_var GCP_PROJECT_ID "$GCP_PROJECT_ID"
set_var GCP_REGION "$GCP_REGION"
set_var GCP_ARTIFACT_REPOSITORY "$GCP_ARTIFACT_REPOSITORY"
record gcp_project_id "$GCP_PROJECT_ID"
record gcp_region "$GCP_REGION"
record artifact_registry "$GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REPOSITORY"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: deploy identity"
say "A deploy service account this repository — and only this repository — can"
say "impersonate through Workload Identity Federation. No key ever leaves GCP."
sa="github-deploy@$GCP_PROJECT_ID.iam.gserviceaccount.com"
gcloud iam service-accounts describe "$sa" --project="$GCP_PROJECT_ID" >/dev/null 2>&1 ||
  gcloud iam service-accounts create github-deploy \
    --display-name="GitHub Actions deploy" --project="$GCP_PROJECT_ID"
for role in roles/run.admin roles/artifactregistry.writer roles/iam.serviceAccountUser; do
  gcloud projects add-iam-policy-binding "$GCP_PROJECT_ID" \
    --member="serviceAccount:$sa" --role="$role" --condition=None >/dev/null
  step "granted $role"
done
gcloud iam workload-identity-pools describe github --location=global \
  --project="$GCP_PROJECT_ID" >/dev/null 2>&1 ||
  gcloud iam workload-identity-pools create github --location=global \
    --display-name="GitHub Actions" --project="$GCP_PROJECT_ID"
pool=$(gcloud iam workload-identity-pools describe github --location=global \
  --project="$GCP_PROJECT_ID" --format='value(name)')
gcloud iam workload-identity-pools providers describe github \
  --workload-identity-pool=github --location=global \
  --project="$GCP_PROJECT_ID" >/dev/null 2>&1 ||
  gcloud iam workload-identity-pools providers create-oidc github \
    --workload-identity-pool=github --location=global --project="$GCP_PROJECT_ID" \
    --issuer-uri="https://token.actions.githubusercontent.com" \
    --attribute-mapping="google.subject=assertion.sub,attribute.repository=assertion.repository" \
    --attribute-condition="assertion.repository=='$REPO'"
provider=$(gcloud iam workload-identity-pools providers describe github \
  --workload-identity-pool=github --location=global \
  --project="$GCP_PROJECT_ID" --format='value(name)')
gcloud iam service-accounts add-iam-policy-binding "$sa" \
  --role=roles/iam.workloadIdentityUser --project="$GCP_PROJECT_ID" \
  --member="principalSet://iam.googleapis.com/$pool/attribute.repository/$REPO" >/dev/null
set_var GCP_DEPLOY_SERVICE_ACCOUNT "$sa"
set_var GCP_WORKLOAD_IDENTITY_PROVIDER "$provider"
record gcp_deploy_service_account "$sa"
record gcp_workload_identity_provider "$provider"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud: Cloud Run service"
say "Created from Google's hello image so the service has a URL before the first"
say "real deploy; Deploy API replaces the image on every push to main."
say "The revision runs as its own service account, which is the identity Secret"
say "Manager grants read access to — the project's default compute account carries"
say "Editor and would read every secret in the project."
CLOUD_RUN_SERVICE=api
RUNTIME_SA="api-runtime@$GCP_PROJECT_ID.iam.gserviceaccount.com"
gcloud iam service-accounts describe "$RUNTIME_SA" --project="$GCP_PROJECT_ID" >/dev/null 2>&1 ||
  gcloud iam service-accounts create api-runtime \
    --display-name="Cloud Run API runtime" --project="$GCP_PROJECT_ID"
if gcloud run services describe "$CLOUD_RUN_SERVICE" --region="$GCP_REGION" \
  --project="$GCP_PROJECT_ID" >/dev/null 2>&1; then
  gcloud run services update "$CLOUD_RUN_SERVICE" --service-account="$RUNTIME_SA" \
    --region="$GCP_REGION" --project="$GCP_PROJECT_ID" --quiet >/dev/null
else
  gcloud run deploy "$CLOUD_RUN_SERVICE" --region="$GCP_REGION" --project="$GCP_PROJECT_ID" \
    --image=us-docker.pkg.dev/cloudrun/container/hello --service-account="$RUNTIME_SA" \
    --allow-unauthenticated --quiet
fi
API_URL=$(gcloud run services describe "$CLOUD_RUN_SERVICE" --region="$GCP_REGION" \
  --project="$GCP_PROJECT_ID" --format='value(status.url)')
say "API URL: $API_URL"
set_var CLOUD_RUN_SERVICE "$CLOUD_RUN_SERVICE"
set_var API_URL "$API_URL"
record cloud_run_service "$CLOUD_RUN_SERVICE"
record cloud_run_runtime_service_account "$RUNTIME_SA"
record api_url "$API_URL"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Vercel: web project"
say "Linking the repo to a Vercel project. Hobby forbids commercial use (ADR 0002)."
vercel link --yes --project "$SLUG"
VERCEL_ORG_ID=$(jq -r .orgId .vercel/project.json)
VERCEL_PROJECT_ID=$(jq -r .projectId .vercel/project.json)
open_url "https://vercel.com/dashboard"
step "Open the '$SLUG' project → Settings → Build and Deployment."
step "Set Root Directory to 'apps/web' and save. No CLI covers this one."
pause "Enter once Root Directory is apps/web."
open_url "https://vercel.com/account/settings/tokens"
step "Create a token scoped to this project's team, then copy it."
ask_secret VERCEL_TOKEN "Paste the Vercel token:"
ask WEB_URL "Production URL of the web app [https://$SLUG.vercel.app]:"
WEB_URL=${WEB_URL:-https://$SLUG.vercel.app}
printf '%s' "$API_URL" | vercel env add API_URL production --force >/dev/null
say "API_URL stored as a Vercel production environment variable"
set_secret VERCEL_TOKEN "$VERCEL_TOKEN"
set_secret VERCEL_ORG_ID "$VERCEL_ORG_ID"
set_secret VERCEL_PROJECT_ID "$VERCEL_PROJECT_ID"
set_var WEB_URL "$WEB_URL"
record vercel_project_id "$VERCEL_PROJECT_ID"
record web_url "$WEB_URL"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "App configuration"
say "The rest of what the API validates at boot (apps/api/src/env.ts)."
set_gcp_secret DATABASE_URL "$DATABASE_URL"
set_gcp_secret AUTH_SECRET "$(openssl rand -hex 32)"
say "AUTH_SECRET generated and stored. Rotating it logs everyone out."
set_var EMAIL_TRANSPORT resend
set_var LLM_PROVIDER google
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Sentry: error tracking"
say "Sentry has no CLI for creating a project or reading its DSN, so this one is manual."
open_url "https://sentry.io/organizations/new/"
step "Create or open an organization, then two projects: '$SLUG-api' (Node) and"
step "'$SLUG-web' (Next.js). Each shows its DSN on the setup page."
ask_secret SENTRY_DSN "Paste the API project DSN:"
ask_secret NEXT_PUBLIC_SENTRY_DSN "Paste the web project DSN:"
set_gcp_secret SENTRY_DSN "$SENTRY_DSN"
printf '%s' "$NEXT_PUBLIC_SENTRY_DSN" | vercel env add NEXT_PUBLIC_SENTRY_DSN production --force >/dev/null
say "web DSN stored as a Vercel production environment variable"
say "The Error Loop reads Sentry's API, but it runs from your terminal, not from CI,"
say "so its token stays in your shell and never becomes a GitHub secret."
open_url "https://sentry.io/settings/account/api/auth-tokens/"
step "Create a token with 'event:read' and 'project:read'."
ask SENTRY_ORG "Sentry organization slug (from the dashboard URL):"
step "Before running /error-loop, export it in that shell:"
step "  SENTRY_ORG=$SENTRY_ORG SENTRY_PROJECT=$SLUG-api SENTRY_AUTH_TOKEN=<the token>"
record sentry_org "$SENTRY_ORG"
record sentry_project "$SLUG-api"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Google AI Studio: Gemini key"
say "POST /ask runs on Gemini Flash, whose free tier costs nothing (ADR 0002)."
open_url "https://aistudio.google.com/apikey"
step "Create an API key, then copy it."
ask_secret GOOGLE_GENERATIVE_AI_API_KEY "Paste the Gemini API key:"
set_gcp_secret GOOGLE_GENERATIVE_AI_API_KEY "$GOOGLE_GENERATIVE_AI_API_KEY"
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Resend: auth email"
say "Verification and password-reset messages go out through Resend."
open_url "https://resend.com/api-keys"
step "Create an API key with send access, then copy it."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
set_gcp_secret RESEND_API_KEY "$RESEND_API_KEY"
pause

record gcp_secrets "${GCP_SECRETS[*]}"
record_write
finish
