name: Error Loop

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  fix:
    uses: Drago96/fullstack-kit/.github/workflows/error-loop.yml@master
    secrets: inherit
